include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    require_trailing_commas: true
analyzer:
  errors:
    invalid_annotation_target: ignore